# Generated by Django 5.0.3 on 2024-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='code',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
