# Generated by Django 5.0.3 on 2024-03-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_usermodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='code',
        ),
    ]
