# Generated by Django 5.0.3 on 2024-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_alter_usermodel_avatar_alter_usermodel_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='secret',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
