# Generated by Django 5.0.3 on 2024-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
