# Generated by Django 5.0.3 on 2024-03-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_foodmodel_created_at_foodmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.foodmodel')),
            ],
        ),
    ]
