# Generated by Django 5.0.3 on 2024-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_foodmodel_quantity_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
