# Generated by Django 5.0.3 on 2024-03-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_final_price_foodmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
