# Generated by Django 5.0.3 on 2024-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
