# Generated by Django 5.0.3 on 2024-03-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cartmodel_finall_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='finall_price',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
