# Generated by Django 5.0.3 on 2024-03-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_cartmodel_food_alter_cartmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='finall_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='products.foodmodel'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
