# Generated by Django 5.0.3 on 2024-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cartmodel_finall_price_alter_cartmodel_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='food'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
